
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FaturaTakip.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FaturaInceleme
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FaturaInceleme()
    {

        this.Fatura = new HashSet<Fatura>();

    }


    public byte Id { get; set; }

    public string IncelemeTuru { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Fatura> Fatura { get; set; }

}

}
